# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  csprojConfig: '**/*.csproj'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
  displayName: Weather App Use 7.x sdk

- task: DotNetCoreCLI@2
  displayName: Weather App Restore
  inputs:
    command: restore
    projects: '$(csprojConfig)'

- task: DotNetCoreCLI@2
  inputs:
    projects: '$(csprojConfig)'
  displayName: Weather App Build

- task: DotNetCoreCLI@2
  displayName: 'Weather App Package Artifacts'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(csprojConfig)'
    arguments: '--configuration $(buildConfiguration) --property:PublishDir=$(build.artifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Weather App Publish Artifacts'
  inputs:
    ArtifactName: WeatherApp
