# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  csproj: '**/*.csproj'

steps:
- task: NuGetToolInstaller@1
  displayName: Weather App Nuget Tools Installation

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: Weather App NuGetCommand

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
  displayName: Weather App Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(csproj)'
    versioningScheme: 'off'
  displayName: 'Weather App Package Artifact'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(csproj)'
    arguments: '--configuration ($buildConfiguration) --property:PublishDir=$(build.artifactStagingDirectory)'
    zipAfterPublish: true
  displayName: 'Weather App Publish Artifacts'
