# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  csproj: '**/*.csproj'

steps:

- task: NuGetToolInstaller@1
  displayName: Weather app Nuget Tools Installation

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: Weather App NuGetCommand

- task: NuGetCommand@2
  displayName: Weather App NuGet Restore
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: Weather App Build

- task: DotNetCoreCLI@2
  displayName: 'Weather App Package Artifacts'
  inputs:
    command: publish
    nobuild: true
    publishWebProjects: false
    projects: 'WeatherApp/WeatherApp.csproj'
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- download: current
  patterns: '**/*.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Weather App Publish Artifacts'
